{% set name = "creosote" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fredrikaverpil/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9c425c50dfb569c57d9f773ac3030c4731ec29628caf7758e9e81cd28c18fd80

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - creosote=creosote.cli:main

requirements:
  host:
    - hatchling
    - python >=3.7
    - pip
  run:
    - dotty-dict >=1.3.1,<1.4
    - loguru >=0.6.0,<0.8
    - pip-requirements-parser >=32.0.1,<33.1
    - python >=3.7
    - toml >=0.10.2,<0.11

test:
  source_files:
    - src
    - tests
    - pyproject.toml
  imports:
    - creosote
  requires:
    - pip
    - pytest
    - pytest-mock
  commands:
    - pip check
    - creosote --help
    - pytest -vvv --capture=tee-sys tests

about:
  home: https://github.com/fredrikaverpil/creosote
  summary: Identify unused dependencies and avoid a bloated virtual environment.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
