{% set name = "creosote" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fredrikaverpil/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 081d5e8fe25885b6fee9b3b4fc535da6e1bcad974dd364168b972049f0376675

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - creosote=creosote.cli:main

requirements:
  host:
    - hatchling
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dotty-dict >=1.3.1,<1.4
    - loguru >=0.6.0,<0.8
    - nbconvert >=7.16.4,<8.0
    - nbformat >=5.10.4,<6.0
    - pip-requirements-parser >=32.0.1,<33.1
    - toml >=0.10.2,<0.11

test:
  source_files:
    - src
    - tests
    - pyproject.toml
  imports:
    - creosote
  requires:
    - pip
    - pytest
    - pytest-mock
  commands:
    - pip check
    - creosote --help
    - pytest -vvv --capture=tee-sys tests

about:
  home: https://github.com/fredrikaverpil/creosote
  summary: Identify unused dependencies and avoid a bloated virtual environment.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
