{% set name = "creosote" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fredrikaverpil/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: af84e1d76a51d653498e0d0b4b9fb561cfd6c1fd9c2d325be025fa82b4965663

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - creosote=creosote.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - dotty-dict >=1.3.1,<1.4
    - loguru >=0.6.0,<0.8
    - nbconvert >=7.16.4,<8.0
    - nbformat >=5.10.4,<6.0
    - pip-requirements-parser >=32.0.1,<33.1
    - tomli >=2.1.0,<3.0.0
    - typing_extensions >=4.12.2

test:
  source_files:
    - src
    - tests
    - pyproject.toml
  imports:
    - creosote
  requires:
    - pip
    - pytest
    - pytest-mock
    - python {{ python_min }}
  commands:
    - pip check
    - creosote --help
    - pytest -vvv --capture=tee-sys tests

about:
  home: https://github.com/fredrikaverpil/creosote
  summary: Identify unused dependencies and avoid a bloated virtual environment.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
